name: Tests
on:
  push:
    branches:
      - develop
jobs:
  test:
    strategy:
      matrix:
        node-version: [16.x, 18.x]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node Runner
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}

      - name: Install Dependencies
        run: |
          npm install
          npx lerna bootstrap --hoist

      - name: Run Unit & Integration Tests
        run: npm test
